[project]
name = "desarrollo-back-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "annan-7", email = "annanrecord@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
desarrollo-back-end = "desarrollo_back_end:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
